CREATE TABLE LOCATION_TYPES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATIONS (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    barcode VARCHAR(255) NOT NULL,
    location_type_id INT NOT NULL,
    FOREIGN KEY (location_type_id) REFERENCES LOCATION_TYPES(id)
);

CREATE TABLE LABWARES (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    barcode VARCHAR(255) NOT NULL,
    location_id INT NOT NULL,
    FOREIGN KEY (location_id) REFERENCES LOCATIONS(id)
);

