CREATE TABLE LOCATION_TYPES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATIONS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BARCODE VARCHAR(255) NOT NULL,
    LOCATION_TYPE_ID INT NOT NULL,
    FOREIGN KEY (LOCATION_TYPE_ID) REFERENCES LOCATION_TYPES(ID)
);

CREATE TABLE LABWARES (
    ID INT PRIMARY KEY,
    NMAE VARCHAR(255) NOT NULL,
    BARCODE VARCHAR(255) NOT NULL,
    LOCATION_ID INT NOT NULL,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
);

